### ISSUE TITLE
Bug - Occasionally NPCs refuse to interact with players

### ISSUE THREAD

**Issue by Bysokar** [StargateMC/IssueTracker#284]
```
[16:30:49][SEVERE/CustomNPCs][noppes.npcs.client.PacketHandlerClient:62] Error with EnumPacketClient.DIALOG
[16:30:49][SEVERE/CustomNPCs][noppes.npcs.client.PacketHandlerClient:62] java.lang.NullPointerException
    at noppes.npcs.client.gui.player.GuiDialogInteract.appendDialog(GuiDialogInteract.java:275)
    at noppes.npcs.client.gui.player.GuiDialogInteract.<init>(GuiDialogInteract.java:50)
    at noppes.npcs.client.NoppesUtil.openDialog(NoppesUtil.java:198)
    at noppes.npcs.client.PacketHandlerClient.client(PacketHandlerClient.java:163)
    at noppes.npcs.client.PacketHandlerClient.lambda$onPacketData$0(PacketHandlerClient.java:60)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.func_181617_a(Util.java:47)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Bysokar** [comment]
Should no longer be an issue.
