### ISSUE TITLE
Bug - prevent fake crash report from adv rocketry laser

### ISSUE THREAD

**Issue by draksterau** [StargateMC/IssueTracker#331]
```
java.lang.NullPointerException: Ticking block entity
        at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:122)
        at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:860)
        at net.minecraftforge.common.ForgeChunkManager.releaseTicket(ForgeChunkManager.java:780)
        at zmaster587.advancedRocketry.satellite.SatelliteLaser.deactivateLaser(SatelliteLaser.java:55)
        at zmaster587.advancedRocketry.tile.multiblock.TileSpaceLaser.func_73660_a(TileSpaceLaser.java:289)
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at com.google.common.collect.LinkedHashMultimap.create(LinkedHashMultimap.java:122)
        at net.minecraftforge.common.ForgeChunkManager.unforceChunk(ForgeChunkManager.java:860)
        at net.minecraftforge.common.ForgeChunkManager.releaseTicket(ForgeChunkManager.java:780)
        at zmaster587.advancedRocketry.satellite.SatelliteLaser.deactivateLaser(SatelliteLaser.java:55)
        at zmaster587.advancedRocketry.tile.multiblock.TileSpaceLaser.func_73660_a(TileSpaceLaser.java:289)

-- Block entity being ticked --
Details:
        Name: minecraft:arspacelaser // zmaster587.advancedRocketry.tile.multiblock.TileSpaceLaser
        Block type: ID #626 (tile.spaceLaser // zmaster587.advancedRocketry.block.BlockLaser // advancedrocketry:spacelaser)
        Block data value: 4 / 0x4 / 0b0100
        Block location: World: (6657,126,6648), Chunk: (at 1,7,8 in 416,415; contains blocks 6656,0,6640 to 6671,255,6655), Region: (13,12; contains chunks 416,384 to 447,415, blocks 6656,0,6144 to 7167,255,6655)
        Actual block type: ID #626 (tile.spaceLaser // zmaster587.advancedRocketry.block.BlockLaser // advancedrocketry:spacelaser)
        Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:1838)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by draksterau** [comment]
This will no longer be an issue. Orbital lasers no longer mine planets, they provide a void mining function.
