### ISSUE TITLE
Bug - Cannot fire gun unless block is behind the entity we are firing at.

### ISSUE THREAD

**Issue by NovaLynxie** [StargateMC/IssueTracker#334]
## Version of the StargateMC Client
v2.9.0 (prior to latest server side update v2.9.1)

## Did you receive an error message? If so, copy it here.
(No error message thrown, only console errors)
[19:09:46] [Client thread/INFO] [STDOUT]: [com.flansmod.common.FlansMod:log:714]: [Flan's Mod] ERROR encoding packet
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: java.lang.NullPointerException
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.guns.raytracing.FlansModRaytracer.WriteToBuffer(FlansModRaytracer.java:289)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.network.PacketShotData.encodeInto(PacketShotData.java:76)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.network.PacketHandler.encode(PacketHandler.java:95)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.network.PacketHandler.encode(PacketHandler.java:40)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.network.PacketHandler.sendToServer(PacketHandler.java:281)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.guns.ItemGun.onUpdateClient(ItemGun.java:520)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.guns.ItemGun.onUpdateEach(ItemGun.java:859)
[19:09:46] [Client thread/INFO] [STDERR]: [com.flansmod.common.network.PacketHandler:encode:105]: 	at com.flansmod.common.guns.ItemGun.func_77663_a(ItemGun.java:851)

## Where are you playing?
- [ ] Single Player
- [x] MultiPlayer (StargateMC.com)
- [ ] MultiPlayer (Not StargateMC.com)

## Is your client modified from what is deployed automaticaly into the Technic Launcher?
- [ ] Yes
- [x] No

## Detail what you have modified in the client here, if applicable
(No changes since last update)

## What would you describe the problem as?
Unable to fire flans gun unless aiming at block through the targeted entity. Affects pretty much any flans mod gun.

## Steps to reproduce the problem
1) Reload the gun if necessary.
2) Aim at entity while no blocks are behind them, only air.
3) Attempt to fire at the entity, gun will appear to fire but not actually use ammo or deal damage.

## How often can you reproduce the issue?
- [x] Always
- [ ] Most of the time
- [ ] Some of the time
- [ ] Rarely

## Can you work around the issue and continue playing?
- [x] Yes
- [ ] No

## How to work around the issue
Make sure target entity is in front of any block and then fire. The gun will consume ammo as expected and deal damage depending on the gun and it's ammunition.

## What do you expect to happen instead?
Should be able to deal damage to entity regardless of whether block is air or solid, instead of spitting out packet errors.

**Comment by draksterau** [comment]
@NovaLynxie Is this still a thing? I downgraded Flansmod to v5.5.1 which fixes a raft of issues that showed up in the Beta versions.

**Comment by NovaLynxie** [comment]
Not sure, I'd have to check again for that. If this has been pushed to live then I can check this once I'm back on again later.
I'll keep you updated on what I find out.

**Comment by NovaLynxie** [comment]
@draksterau it still happens as of v3.8.9 of StargateMC live. I've tested firing a weapon into air and not at an entity will still spit out the same error in console.

**Comment by CaptainNikolaus** [comment]
this is working as of testing today
