### ISSUE TITLE
SinglePlayer Crash

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/IssueTracker#44]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ChunkAnimator-1.2.jar)
  WarpDriveCore (WarpDrive-1.5.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.6.3.jar)
  SoundUnpack (OpenSecurity-1.0.39.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.6.0.jar)
  MalisisCorePlugin (MalisisCore-6.5.1b.jar)
  TransformerLoader (OpenComputers-1.7.5.192.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-92.jar)
  CTMCorePlugin (CTM-1.0.1.30.jar)
  MekanismCoremod (Mekanism-9.8.3.390.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 2/10/20 9:14 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Advanced Rocketry (advancedrocketry)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 6
	at java.lang.String.substring(Unknown Source)
	at zmaster587.advancedRocketry.dimension.DimensionManager.getNextName(DimensionManager.java:204)
	at zmaster587.advancedRocketry.dimension.DimensionManager.generateRandom(DimensionManager.java:322)
	at zmaster587.advancedRocketry.AdvancedRocketry.generateRandomPlanets(AdvancedRocketry.java:1595)
	at zmaster587.advancedRocketry.AdvancedRocketry.serverStarting(AdvancedRocketry.java:1388)
```

**Comment by StargateMC** [comment]
Fixed in https://github.com/StargateMC/StargateMC/commit/b4b16092cb6118d39f4724b063e13ea57dca370d
