### ISSUE TITLE
Client Crash when NPCs Firing Weapons

### ISSUE THREAD

**Issue by StargateMC** [StargateMC/IssueTracker#82]
`// Don't be sad, have a hug! <3

Time: 2/28/20 3:06 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at zmaster587.advancedRocketry.dimension.DimensionProperties.getSunColor(DimensionProperties.java:407)
	at zmaster587.advancedRocketry.world.provider.WorldProviderPlanet.getSunColor(WorldProviderPlanet.java:425)
	at zmaster587.advancedRocketry.client.render.planet.RenderPlanetarySky.render(RenderPlanetarySky.java:221)
	at net.minecraft.client.renderer.RenderGlobal.func_174976_a(RenderGlobal.java:1274)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1296)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

**Comment by StargateMC** [comment]
Fixed by reverting flans to 5.5.2

**Comment by StargateMC** [comment]
Fixed by updating AR.
